name: flutter_app
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Common
  get: ^4.6.3
  get_storage: ^2.0.3
  responsive_builder: ^0.4.2
  provider: ^6.0.2
  cached_network_image: ^3.2.0
  overlay_support: ^2.0.0
  flutter_svg: ^1.0.3

  #  Network
  dio: ^4.0.6
  connectivity_plus: ^2.3.0
  logger: ^1.1.0

   # Notification
  flutter_local_notifications: ^9.5.3+1
  firebase_messaging: ^14.2.1

  # Firebase
  firebase_analytics: ^10.0.6
  firebase_core: ^2.3.0
  cloud_firestore: ^4.1.0
  firebase_storage: ^11.0.6
  firebase_auth: ^4.1.3

  # Login social
  google_sign_in: ^5.3.1
  flutter_facebook_auth: ^4.3.4
  sign_in_with_apple: ^3.3.0
  flutter_zalo_login: ^0.1.9+1

  #Other
  flutter_staggered_animations: ^1.0.0
  shimmer: ^2.0.0
  modal_bottom_sheet: ^2.0.1
  flutter_slidable: ^1.2.1
  photo_view: ^0.13.0
  device_info: ^2.0.3
  equatable: ^2.0.3
  supercharged: ^2.1.1
  flutter_spinkit: ^5.1.0
  keyboard_dismisser: ^2.0.1
  flutter_keyboard_visibility: ^5.2.0
  flutter_screenutil: ^5.7.0


dependency_overrides:
  platform: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^2.0.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/inter/Inter-Black.ttf
          weight: 900
        - asset: assets/fonts/inter/Inter-Black.ttf
          weight: 800
        - asset: assets/fonts/inter/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/inter/Inter-Bold.ttf
          weight: 600
        - asset: assets/fonts/inter/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/inter/Inter-Medium.ttf
          weight: 400
        - asset: assets/fonts/inter/Inter-Regular.ttf
          weight: 300
        - asset: assets/fonts/inter/Inter-Light.ttf
          weight: 200
        - asset: assets/fonts/inter/Inter-Light.ttf
          weight: 100
    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto/Roboto-Black.ttf
          weight: 900
        - asset: assets/fonts/roboto/Roboto-Black.ttf
          weight: 800
        - asset: assets/fonts/roboto/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/roboto/Roboto-Bold.ttf
          weight: 600
        - asset: assets/fonts/roboto/Roboto-Regular.ttf
          weight: 500
        - asset: assets/fonts/roboto/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/roboto/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/roboto/Roboto-Light.ttf
          weight: 200
        - asset: assets/fonts/roboto/Roboto-Light.ttf
          weight: 100